<?php
/**
 * BillableMetricsApi
 * PHP version 7.4
 *
 * @category Class
 * @package  LagoClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Lago API documentation
 *
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 0.37.0-beta
 * Contact: tech@getlago.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace LagoClient\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use LagoClient\ApiException;
use LagoClient\Configuration;
use LagoClient\HeaderSelector;
use LagoClient\ObjectSerializer;

/**
 * BillableMetricsApi Class Doc Comment
 *
 * @category Class
 * @package  LagoClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BillableMetricsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createBillableMetric' => [
            'application/json',
        ],
        'destroyBillableMetric' => [
            'application/json',
        ],
        'findAllBillableMetricGroups' => [
            'application/json',
        ],
        'findAllBillableMetrics' => [
            'application/json',
        ],
        'findBillableMetric' => [
            'application/json',
        ],
        'updateBillableMetric' => [
            'application/json',
        ],
    ];

/**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createBillableMetric
     *
     * Create a billable metric
     *
     * @param  \LagoClient\Model\BillableMetricCreateInput $billable_metric_create_input Billable metric payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createBillableMetric'] to see the possible values for this operation
     *
     * @throws \LagoClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \LagoClient\Model\BillableMetric
     */
    public function createBillableMetric($billable_metric_create_input, string $contentType = self::contentTypes['createBillableMetric'][0])
    {
        list($response) = $this->createBillableMetricWithHttpInfo($billable_metric_create_input, $contentType);
        return $response;
    }

    /**
     * Operation createBillableMetricWithHttpInfo
     *
     * Create a billable metric
     *
     * @param  \LagoClient\Model\BillableMetricCreateInput $billable_metric_create_input Billable metric payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createBillableMetric'] to see the possible values for this operation
     *
     * @throws \LagoClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \LagoClient\Model\BillableMetric, HTTP status code, HTTP response headers (array of strings)
     */
    public function createBillableMetricWithHttpInfo($billable_metric_create_input, string $contentType = self::contentTypes['createBillableMetric'][0])
    {
        $request = $this->createBillableMetricRequest($billable_metric_create_input, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\LagoClient\Model\BillableMetric' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\LagoClient\Model\BillableMetric' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\LagoClient\Model\BillableMetric', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\LagoClient\Model\BillableMetric';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LagoClient\Model\BillableMetric',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation createBillableMetricAsync
     *
     * Create a billable metric
     *
     * @param  \LagoClient\Model\BillableMetricCreateInput $billable_metric_create_input Billable metric payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createBillableMetric'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createBillableMetricAsync($billable_metric_create_input, string $contentType = self::contentTypes['createBillableMetric'][0])
    {
        return $this->createBillableMetricAsyncWithHttpInfo($billable_metric_create_input, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createBillableMetricAsyncWithHttpInfo
     *
     * Create a billable metric
     *
     * @param  \LagoClient\Model\BillableMetricCreateInput $billable_metric_create_input Billable metric payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createBillableMetric'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createBillableMetricAsyncWithHttpInfo($billable_metric_create_input, string $contentType = self::contentTypes['createBillableMetric'][0])
    {
        $returnType = '\LagoClient\Model\BillableMetric';
        $request = $this->createBillableMetricRequest($billable_metric_create_input, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createBillableMetric'
     *
     * @param  \LagoClient\Model\BillableMetricCreateInput $billable_metric_create_input Billable metric payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createBillableMetric'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createBillableMetricRequest($billable_metric_create_input, string $contentType = self::contentTypes['createBillableMetric'][0])
    {

        // verify the required parameter 'billable_metric_create_input' is set
        if ($billable_metric_create_input === null || (is_array($billable_metric_create_input) && count($billable_metric_create_input) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $billable_metric_create_input when calling createBillableMetric'
            );
        }


        $resourcePath = '/billable_metrics';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($billable_metric_create_input)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($billable_metric_create_input));
            } else {
                $httpBody = $billable_metric_create_input;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation destroyBillableMetric
     *
     * Delete a billable metric
     *
     * @param  string $code Code of the existing billable metric. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['destroyBillableMetric'] to see the possible values for this operation
     *
     * @throws \LagoClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \LagoClient\Model\BillableMetric
     */
    public function destroyBillableMetric($code, string $contentType = self::contentTypes['destroyBillableMetric'][0])
    {
        list($response) = $this->destroyBillableMetricWithHttpInfo($code, $contentType);
        return $response;
    }

    /**
     * Operation destroyBillableMetricWithHttpInfo
     *
     * Delete a billable metric
     *
     * @param  string $code Code of the existing billable metric. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['destroyBillableMetric'] to see the possible values for this operation
     *
     * @throws \LagoClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \LagoClient\Model\BillableMetric, HTTP status code, HTTP response headers (array of strings)
     */
    public function destroyBillableMetricWithHttpInfo($code, string $contentType = self::contentTypes['destroyBillableMetric'][0])
    {
        $request = $this->destroyBillableMetricRequest($code, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\LagoClient\Model\BillableMetric' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\LagoClient\Model\BillableMetric' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\LagoClient\Model\BillableMetric', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\LagoClient\Model\BillableMetric';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LagoClient\Model\BillableMetric',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation destroyBillableMetricAsync
     *
     * Delete a billable metric
     *
     * @param  string $code Code of the existing billable metric. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['destroyBillableMetric'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function destroyBillableMetricAsync($code, string $contentType = self::contentTypes['destroyBillableMetric'][0])
    {
        return $this->destroyBillableMetricAsyncWithHttpInfo($code, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation destroyBillableMetricAsyncWithHttpInfo
     *
     * Delete a billable metric
     *
     * @param  string $code Code of the existing billable metric. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['destroyBillableMetric'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function destroyBillableMetricAsyncWithHttpInfo($code, string $contentType = self::contentTypes['destroyBillableMetric'][0])
    {
        $returnType = '\LagoClient\Model\BillableMetric';
        $request = $this->destroyBillableMetricRequest($code, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'destroyBillableMetric'
     *
     * @param  string $code Code of the existing billable metric. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['destroyBillableMetric'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function destroyBillableMetricRequest($code, string $contentType = self::contentTypes['destroyBillableMetric'][0])
    {

        // verify the required parameter 'code' is set
        if ($code === null || (is_array($code) && count($code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $code when calling destroyBillableMetric'
            );
        }


        $resourcePath = '/billable_metrics/{code}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($code !== null) {
            $resourcePath = str_replace(
                '{' . 'code' . '}',
                ObjectSerializer::toPathValue($code),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation findAllBillableMetricGroups
     *
     * Find a billable metric&#39;s groups
     *
     * @param  string $code Code of the existing billable metric. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findAllBillableMetricGroups'] to see the possible values for this operation
     *
     * @throws \LagoClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \LagoClient\Model\GroupsPaginated
     */
    public function findAllBillableMetricGroups($code, string $contentType = self::contentTypes['findAllBillableMetricGroups'][0])
    {
        list($response) = $this->findAllBillableMetricGroupsWithHttpInfo($code, $contentType);
        return $response;
    }

    /**
     * Operation findAllBillableMetricGroupsWithHttpInfo
     *
     * Find a billable metric&#39;s groups
     *
     * @param  string $code Code of the existing billable metric. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findAllBillableMetricGroups'] to see the possible values for this operation
     *
     * @throws \LagoClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \LagoClient\Model\GroupsPaginated, HTTP status code, HTTP response headers (array of strings)
     */
    public function findAllBillableMetricGroupsWithHttpInfo($code, string $contentType = self::contentTypes['findAllBillableMetricGroups'][0])
    {
        $request = $this->findAllBillableMetricGroupsRequest($code, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\LagoClient\Model\GroupsPaginated' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\LagoClient\Model\GroupsPaginated' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\LagoClient\Model\GroupsPaginated', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\LagoClient\Model\GroupsPaginated';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LagoClient\Model\GroupsPaginated',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation findAllBillableMetricGroupsAsync
     *
     * Find a billable metric&#39;s groups
     *
     * @param  string $code Code of the existing billable metric. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findAllBillableMetricGroups'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findAllBillableMetricGroupsAsync($code, string $contentType = self::contentTypes['findAllBillableMetricGroups'][0])
    {
        return $this->findAllBillableMetricGroupsAsyncWithHttpInfo($code, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation findAllBillableMetricGroupsAsyncWithHttpInfo
     *
     * Find a billable metric&#39;s groups
     *
     * @param  string $code Code of the existing billable metric. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findAllBillableMetricGroups'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findAllBillableMetricGroupsAsyncWithHttpInfo($code, string $contentType = self::contentTypes['findAllBillableMetricGroups'][0])
    {
        $returnType = '\LagoClient\Model\GroupsPaginated';
        $request = $this->findAllBillableMetricGroupsRequest($code, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'findAllBillableMetricGroups'
     *
     * @param  string $code Code of the existing billable metric. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findAllBillableMetricGroups'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function findAllBillableMetricGroupsRequest($code, string $contentType = self::contentTypes['findAllBillableMetricGroups'][0])
    {

        // verify the required parameter 'code' is set
        if ($code === null || (is_array($code) && count($code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $code when calling findAllBillableMetricGroups'
            );
        }


        $resourcePath = '/billable_metrics/{code}/groups';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($code !== null) {
            $resourcePath = str_replace(
                '{' . 'code' . '}',
                ObjectSerializer::toPathValue($code),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation findAllBillableMetrics
     *
     * List all billable metrics
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findAllBillableMetrics'] to see the possible values for this operation
     *
     * @throws \LagoClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \LagoClient\Model\BillableMetricsPaginated
     */
    public function findAllBillableMetrics(string $contentType = self::contentTypes['findAllBillableMetrics'][0])
    {
        list($response) = $this->findAllBillableMetricsWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation findAllBillableMetricsWithHttpInfo
     *
     * List all billable metrics
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findAllBillableMetrics'] to see the possible values for this operation
     *
     * @throws \LagoClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \LagoClient\Model\BillableMetricsPaginated, HTTP status code, HTTP response headers (array of strings)
     */
    public function findAllBillableMetricsWithHttpInfo(string $contentType = self::contentTypes['findAllBillableMetrics'][0])
    {
        $request = $this->findAllBillableMetricsRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\LagoClient\Model\BillableMetricsPaginated' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\LagoClient\Model\BillableMetricsPaginated' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\LagoClient\Model\BillableMetricsPaginated', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\LagoClient\Model\BillableMetricsPaginated';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LagoClient\Model\BillableMetricsPaginated',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation findAllBillableMetricsAsync
     *
     * List all billable metrics
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findAllBillableMetrics'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findAllBillableMetricsAsync(string $contentType = self::contentTypes['findAllBillableMetrics'][0])
    {
        return $this->findAllBillableMetricsAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation findAllBillableMetricsAsyncWithHttpInfo
     *
     * List all billable metrics
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findAllBillableMetrics'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findAllBillableMetricsAsyncWithHttpInfo(string $contentType = self::contentTypes['findAllBillableMetrics'][0])
    {
        $returnType = '\LagoClient\Model\BillableMetricsPaginated';
        $request = $this->findAllBillableMetricsRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'findAllBillableMetrics'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findAllBillableMetrics'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function findAllBillableMetricsRequest(string $contentType = self::contentTypes['findAllBillableMetrics'][0])
    {


        $resourcePath = '/billable_metrics';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation findBillableMetric
     *
     * Retrieve a billable metric
     *
     * @param  string $code Code of the existing billable metric. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findBillableMetric'] to see the possible values for this operation
     *
     * @throws \LagoClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \LagoClient\Model\BillableMetric
     */
    public function findBillableMetric($code, string $contentType = self::contentTypes['findBillableMetric'][0])
    {
        list($response) = $this->findBillableMetricWithHttpInfo($code, $contentType);
        return $response;
    }

    /**
     * Operation findBillableMetricWithHttpInfo
     *
     * Retrieve a billable metric
     *
     * @param  string $code Code of the existing billable metric. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findBillableMetric'] to see the possible values for this operation
     *
     * @throws \LagoClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \LagoClient\Model\BillableMetric, HTTP status code, HTTP response headers (array of strings)
     */
    public function findBillableMetricWithHttpInfo($code, string $contentType = self::contentTypes['findBillableMetric'][0])
    {
        $request = $this->findBillableMetricRequest($code, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\LagoClient\Model\BillableMetric' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\LagoClient\Model\BillableMetric' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\LagoClient\Model\BillableMetric', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\LagoClient\Model\BillableMetric';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LagoClient\Model\BillableMetric',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation findBillableMetricAsync
     *
     * Retrieve a billable metric
     *
     * @param  string $code Code of the existing billable metric. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findBillableMetric'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findBillableMetricAsync($code, string $contentType = self::contentTypes['findBillableMetric'][0])
    {
        return $this->findBillableMetricAsyncWithHttpInfo($code, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation findBillableMetricAsyncWithHttpInfo
     *
     * Retrieve a billable metric
     *
     * @param  string $code Code of the existing billable metric. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findBillableMetric'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findBillableMetricAsyncWithHttpInfo($code, string $contentType = self::contentTypes['findBillableMetric'][0])
    {
        $returnType = '\LagoClient\Model\BillableMetric';
        $request = $this->findBillableMetricRequest($code, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'findBillableMetric'
     *
     * @param  string $code Code of the existing billable metric. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findBillableMetric'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function findBillableMetricRequest($code, string $contentType = self::contentTypes['findBillableMetric'][0])
    {

        // verify the required parameter 'code' is set
        if ($code === null || (is_array($code) && count($code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $code when calling findBillableMetric'
            );
        }


        $resourcePath = '/billable_metrics/{code}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($code !== null) {
            $resourcePath = str_replace(
                '{' . 'code' . '}',
                ObjectSerializer::toPathValue($code),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateBillableMetric
     *
     * Update a billable metric
     *
     * @param  string $code Code of the existing billable metric. (required)
     * @param  \LagoClient\Model\BillableMetricUpdateInput $billable_metric_update_input Billable metric payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateBillableMetric'] to see the possible values for this operation
     *
     * @throws \LagoClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \LagoClient\Model\BillableMetric
     */
    public function updateBillableMetric($code, $billable_metric_update_input, string $contentType = self::contentTypes['updateBillableMetric'][0])
    {
        list($response) = $this->updateBillableMetricWithHttpInfo($code, $billable_metric_update_input, $contentType);
        return $response;
    }

    /**
     * Operation updateBillableMetricWithHttpInfo
     *
     * Update a billable metric
     *
     * @param  string $code Code of the existing billable metric. (required)
     * @param  \LagoClient\Model\BillableMetricUpdateInput $billable_metric_update_input Billable metric payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateBillableMetric'] to see the possible values for this operation
     *
     * @throws \LagoClient\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \LagoClient\Model\BillableMetric, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateBillableMetricWithHttpInfo($code, $billable_metric_update_input, string $contentType = self::contentTypes['updateBillableMetric'][0])
    {
        $request = $this->updateBillableMetricRequest($code, $billable_metric_update_input, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\LagoClient\Model\BillableMetric' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\LagoClient\Model\BillableMetric' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\LagoClient\Model\BillableMetric', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\LagoClient\Model\BillableMetric';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LagoClient\Model\BillableMetric',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation updateBillableMetricAsync
     *
     * Update a billable metric
     *
     * @param  string $code Code of the existing billable metric. (required)
     * @param  \LagoClient\Model\BillableMetricUpdateInput $billable_metric_update_input Billable metric payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateBillableMetric'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateBillableMetricAsync($code, $billable_metric_update_input, string $contentType = self::contentTypes['updateBillableMetric'][0])
    {
        return $this->updateBillableMetricAsyncWithHttpInfo($code, $billable_metric_update_input, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateBillableMetricAsyncWithHttpInfo
     *
     * Update a billable metric
     *
     * @param  string $code Code of the existing billable metric. (required)
     * @param  \LagoClient\Model\BillableMetricUpdateInput $billable_metric_update_input Billable metric payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateBillableMetric'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateBillableMetricAsyncWithHttpInfo($code, $billable_metric_update_input, string $contentType = self::contentTypes['updateBillableMetric'][0])
    {
        $returnType = '\LagoClient\Model\BillableMetric';
        $request = $this->updateBillableMetricRequest($code, $billable_metric_update_input, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateBillableMetric'
     *
     * @param  string $code Code of the existing billable metric. (required)
     * @param  \LagoClient\Model\BillableMetricUpdateInput $billable_metric_update_input Billable metric payload (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateBillableMetric'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function updateBillableMetricRequest($code, $billable_metric_update_input, string $contentType = self::contentTypes['updateBillableMetric'][0])
    {

        // verify the required parameter 'code' is set
        if ($code === null || (is_array($code) && count($code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $code when calling updateBillableMetric'
            );
        }

        // verify the required parameter 'billable_metric_update_input' is set
        if ($billable_metric_update_input === null || (is_array($billable_metric_update_input) && count($billable_metric_update_input) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $billable_metric_update_input when calling updateBillableMetric'
            );
        }


        $resourcePath = '/billable_metrics/{code}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($code !== null) {
            $resourcePath = str_replace(
                '{' . 'code' . '}',
                ObjectSerializer::toPathValue($code),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($billable_metric_update_input)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($billable_metric_update_input));
            } else {
                $httpBody = $billable_metric_update_input;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
